facetapi.facet.*:
  type: config_entity
  label : 'Facet'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: Name'
    uuid:
      type: string
      label: 'UUID'
    status:
      type: boolean
      label: 'Status'
    facet_source:
      type: string
      label: 'Facet source'
    field_identifier:
      type: string
      label: 'Field identifier'
    query_type_name:
      type: string
      label: 'Query Type Name'
    widget:
      type: string
      label: 'Field identifier'
    widget_configs:
      type: sequence
      label: 'Widget plugin configurations'
      sequence:
        type: string
        label: 'Widget plugin configurations'
    processor_configs:
      type: sequence
      label: 'Configuration for processors'
      sequence:
        id:
          type: string
          label: 'Plugin name'
        settings:
          type: sequence
          label: 'Plugin setting'
          sequence:
            type: string
